// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAISo1iBKg6oNiMou4eZtpskWX6CcZOsQ',
    appId: '1:327427771470:web:3c28ab6d907a117247471f',
    messagingSenderId: '327427771470',
    projectId: 'mc-5450-challenge3',
    authDomain: 'mc-5450-challenge3.firebaseapp.com',
    storageBucket: 'mc-5450-challenge3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1FDrQE1yQEzZKvlHgurvaOCGOsREkY8',
    appId: '1:327427771470:android:93695691c8fa9ca247471f',
    messagingSenderId: '327427771470',
    projectId: 'mc-5450-challenge3',
    storageBucket: 'mc-5450-challenge3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcUfMknRk8D2Gbs0sqKA_h1B2ZloVKrM',
    appId: '1:327427771470:ios:62e82037e667a85e47471f',
    messagingSenderId: '327427771470',
    projectId: 'mc-5450-challenge3',
    storageBucket: 'mc-5450-challenge3.firebasestorage.app',
    iosBundleId: 'com.example.mastermindGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXcUfMknRk8D2Gbs0sqKA_h1B2ZloVKrM',
    appId: '1:327427771470:ios:62e82037e667a85e47471f',
    messagingSenderId: '327427771470',
    projectId: 'mc-5450-challenge3',
    storageBucket: 'mc-5450-challenge3.firebasestorage.app',
    iosBundleId: 'com.example.mastermindGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAISo1iBKg6oNiMou4eZtpskWX6CcZOsQ',
    appId: '1:327427771470:web:750db84887c8def047471f',
    messagingSenderId: '327427771470',
    projectId: 'mc-5450-challenge3',
    authDomain: 'mc-5450-challenge3.firebaseapp.com',
    storageBucket: 'mc-5450-challenge3.firebasestorage.app',
  );
}
